<?php
    $troca = array('linha',',');
    $Trocas = array(' ','-','.',')','(');
    require_once("conexao.php");
    $conexao = conexao::getInstance();
    require_once("../arquivo/funcao/Outras.php");
    // Atribui uma conexão PDO
    $x = 0;
    $Celular = "0";
    $Telefone = "0";
    $Email = "* Nenhum Registro *";
    /*echo "<pre>";
    var_dump($_POST);
    echo "</pre>";*/
    if(isset($_POST['Colaborador']) && $_POST['Colaborador']  ==  "Cadastro"):
        $c = str_split(str_replace($troca,'',$_POST['hidden1']));
        $cont = count($c);
        if($_POST['celular'] != "" || $_POST['telefone'] != ""):
            if($_POST['celular'] != ""):
                $Celular = anti_injection($_POST['celular']);
                $Celular = str_replace($Trocas,"",$Celular);
            endif;
            if($_POST['telefone']!= ""):
                $Telefone = anti_injection($_POST['telefone']);
                $Telefone = str_replace($Trocas,"",$Telefone);
            endif;
        else:
            echo "<script>alert('Digite pelo menos um número para contato!');window.setTimeout('history.go(-1)', 0);</script>";exit;
        endif;
        if($_POST['email'] != ""):
            if(!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL)):
                echo "<script>alert('Formato de e-mail incorreto!');window.setTimeout('history.go(-1)', 0);</script>";
            else:
                $Email = anti_injection($_POST['email']);
            endif;
        endif; 
        $Nome = anti_injection(utf8_encode($_POST['nome']));
        $CPF = str_replace($Trocas,"",$_POST['cpf']);
        $SQL = "INSERT INTO cadastro (Nome, CPF) VALUES (?,?)";
        $stmt = $conexao->prepare($SQL);
        $stmt->bindParam(1, $Nome);
        $stmt->bindParam(2, $CPF);
        $Cadastro = $stmt->execute();
        if($Cadastro):
            $IdCadastro = $conexao->lastInsertId();
            $SQL = "INSERT INTO contato (Telefone, Celular, email) VALUES (?,?,?)";
            $stmt = $conexao->prepare($SQL);
            $stmt->bindParam(1, $Telefone);
            $stmt->bindParam(2, $Celular);
            $stmt->bindParam(3, $Email);
            $Contato = $stmt->execute();
            if($Contato):
                $IdContato = $conexao->lastInsertId();
                $Endereco = anti_injection(utf8_encode($_POST['logradouro']));
                $Bairro = anti_injection(utf8_encode($_POST['bairro']));
                $CEP = str_replace($Trocas,"",$_POST['cep']);
                $Cidade = anti_injection(utf8_encode($_POST['cidade']));
                $Numero = anti_injection(utf8_encode($_POST['numero']));
                $UF = anti_injection(utf8_encode($_POST['uf']));
                $SQL = "INSERT INTO endereco (Endereco, Bairro, CEP, Cidade, Numero, UF) VALUES (?,?,?,?,?,?)";
                $stmt = $conexao->prepare($SQL);
                $stmt->bindParam(1, $Endereco);
                $stmt->bindParam(2, $Bairro);
                $stmt->bindParam(3, $CEP);
                $stmt->bindParam(4, $Cidade);
                $stmt->bindParam(5, $Numero);
                $stmt->bindParam(6, $UF);
                $Endereco = $stmt->execute();
                if($Endereco):
                    $IdEndereco = $conexao->lastInsertId();
                    $RG = str_replace($Trocas,"",$_POST['RG']);
                    $Emissor = anti_injection(utf8_encode($_POST['emissor']));
                    $dEmissao = anti_injection(utf8_encode($_POST['dEmissao']));
                    $Titulo = anti_injection(utf8_encode($_POST['titulo']));
                    $Secao = anti_injection(utf8_encode($_POST['secao']));
                    $Zona = anti_injection(utf8_encode($_POST['Zona']));
                    if($_POST['cnh'] == ""):
                        if($_POST['militar'] == ""):
                            $SQL = "INSERT INTO documento (RG, Emissor, dEmissao, Titulo, Zona, Secao) VALUES (?,?,?,?,?,?)";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $RG);
                            $stmt->bindParam(2, $Emissor);
                            $stmt->bindParam(3, $dEmissao);
                            $stmt->bindParam(4, $Titulo);
                            $stmt->bindParam(5, $Secao);
                            $stmt->bindParam(6, $Zona);
                            $Documento = $stmt->execute();
                        else:
                            $dMilitar = $_POST['militar'];
                            $sMilitar = $_POST['cMilitar'];
                            $SQL = "INSERT INTO documento (RG, Emissor, dEmissao, Titulo, Zona, Secao,docMilitar,mCategoria) VALUES (?,?,?,?,?,?,?,?)";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $RG);
                            $stmt->bindParam(2, $Emissor);
                            $stmt->bindParam(3, $dEmissao);
                            $stmt->bindParam(4, $Titulo);
                            $stmt->bindParam(5, $Secao);
                            $stmt->bindParam(6, $Zona);
                            $stmt->bindParam(7, $dMilitar);
                            $stmt->bindParam(8, $sMilitar);
                            $Documento = $stmt->execute();
                        endif;
                    else:
                        if($_POST['militar'] == ""):
                            $CNH = str_replace($Trocas,"",$_POST['cnh']);
                            $CategoriaCNH = anti_injection(utf8_encode($_POST['categoria']));
                            $ValidadeCNH = anti_injection(utf8_encode($_POST['validade']));
                            $dMilitar = $_POST['militar'];
                            $sMilitar = $_POST['cMilitar'];
                            $SQL = "INSERT INTO documento (RG, Emissor, dEmissao, Titulo, Zona, Secao, CNH, CategoriaCNH, Validade) VALUES (?,?,?,?,?,?,?,?,?)";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $RG);
                            $stmt->bindParam(2, $Emissor);
                            $stmt->bindParam(3, $dEmissao);
                            $stmt->bindParam(4, $Titulo);
                            $stmt->bindParam(5, $Zona);
                            $stmt->bindParam(6, $Secao);
                            $stmt->bindParam(7, $CNH);
                            $stmt->bindParam(8, $CategoriaCNH);
                            $stmt->bindParam(9, $ValidadeCNH);
                            $Documento = $stmt->execute();
                        else:
                            $CNH = str_replace($Trocas,"",$_POST['cnh']);
                            $CategoriaCNH = anti_injection(utf8_encode($_POST['categoria']));
                            $ValidadeCNH = anti_injection(utf8_encode($_POST['validade']));
                            $dMilitar = $_POST['militar'];
                            $sMilitar = $_POST['cMilitar'];
                            $SQL = "INSERT INTO documento (RG, Emissor, dEmissao, Titulo, Zona, Secao, CNH, CategoriaCNH, Validade,docMilitar,mCategoria) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $RG);
                            $stmt->bindParam(2, $Emissor);
                            $stmt->bindParam(3, $dEmissao);
                            $stmt->bindParam(4, $Titulo);
                            $stmt->bindParam(5, $Zona);
                            $stmt->bindParam(6, $Secao);
                            $stmt->bindParam(7, $CNH);
                            $stmt->bindParam(8, $CategoriaCNH);
                            $stmt->bindParam(9, $ValidadeCNH);
                            $stmt->bindParam(10, $dMilitar);
                            $stmt->bindParam(11, $sMilitar);
                            $Documento = $stmt->execute();
                        endif;
                    endif;
                    if($Documento):
                        $IdDocumento = $conexao->lastInsertId();
                        $dAdmissao = anti_injection(utf8_encode($_POST['dAdmissao']));
                        $CTPS = anti_injection(utf8_encode($_POST['ctps']));
                        $sCTPS = anti_injection(utf8_encode($_POST['sCtps']));
                        $dCTPS = anti_injection(utf8_encode($_POST['dCtps']));
                        $UCTPS = anti_injection(utf8_encode($_POST['uCtps']));
                        $PIS = anti_injection(utf8_encode($_POST['pis']));
                        $dIntegracao = anti_injection(utf8_encode($_POST['dIntegracao']));
                        $dAso = anti_injection(utf8_encode($_POST['dAso']));
                        $Cargo = anti_injection(utf8_encode($_POST['cargo']));
                        $SQL = "INSERT INTO contratacao (Unidade_idUnidade, dAdmissao, CTPS, sCTPS, UFCTPS, dCTPS, PIS, dIntegracao, dASO,  Cargo_idCargo) VALUES (?,?,?,?,?,?,?,?,?,?)";
                        $stmt = $conexao->prepare($SQL);
                        $stmt->bindParam(1, $_POST['unidade']);
                        $stmt->bindParam(2, $dAdmissao);
                        $stmt->bindParam(3, $CTPS);
                        $stmt->bindParam(4, $sCTPS);
                        $stmt->bindParam(5, $UCTPS);
                        $stmt->bindParam(6, $dCTPS);
                        $stmt->bindParam(7, $PIS);
                        $stmt->bindParam(8, $dIntegracao);
                        $stmt->bindParam(9, $dAso);
                        $stmt->bindParam(10, $Cargo);
                        $Contratacao = $stmt->execute();
                        if($Contratacao):
                            $IdContratacao = $conexao->lastInsertId();
                            $Sexo = anti_injection(utf8_encode($_POST['sexo']));
                            $Naturalidade = anti_injection(utf8_encode($_POST['naturalidade']));
                            $Cor = anti_injection(utf8_encode($_POST['cor']));
                            $Escolaridade = anti_injection(utf8_encode($_POST['gInstrucao']));
                            $eCivl = anti_injection(utf8_encode($_POST['eCivil']));
                            $nPai = anti_injection(utf8_encode($_POST['nPai']));
                            $nMae = anti_injection(utf8_encode($_POST['nMae']));
                            if($_POST['conjugue'] == ""):
                                $SQL = "INSERT INTO colaborador (Cadastro_idCadastro, Endereco_idEndereco, Documento_idDocumento, Contratacao_idContratacao, Contato_idContato, Sexo, Naturalidade, Cor, Escolaridade, eCivil, nPai, nMae, dNascimento,CodColaborador) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                                $stmt = $conexao->prepare($SQL);
                                $stmt->bindParam(1, $IdCadastro);
                                $stmt->bindParam(2, $IdEndereco);
                                $stmt->bindParam(3, $IdDocumento);
                                $stmt->bindParam(4, $IdContratacao);
                                $stmt->bindParam(5, $IdContato);
                                $stmt->bindParam(6, $Sexo);
                                $stmt->bindParam(7, $Naturalidade);
                                $stmt->bindParam(8, $Cor);
                                $stmt->bindParam(9, $Escolaridade);
                                $stmt->bindParam(10, $eCivl);
                                $stmt->bindParam(11, $nPai);
                                $stmt->bindParam(12, $nMae);
                                $stmt->bindParam(13, $_POST['dNascimento']);
                                $stmt->bindParam(14, $_POST['CodColaborador']);
                                $Colaborador = $stmt->execute();
                            else:
                                $nConjugue = anti_injection(utf8_encode($_POST['conjugue']));
                                $dNascimentoConjugue = anti_injection(utf8_encode($_POST['dConjugue']));
                                $mConjugue = anti_injection(utf8_encode($_POST['mConjugue']));
                                $cCasamento = anti_injection(utf8_encode($_POST['cCasamento']));
                                $CPFConjugue = str_replace($Trocas,"",anti_injection(utf8_encode($_POST['cpfConjugue'])));
                                $SQL = "INSERT INTO colaborador (Cadastro_idCadastro, Endereco_idEndereco, Documento_idDocumento, Contratacao_idContratacao, Contato_idContato, Sexo, Naturalidade, Cor, Escolaridade, eCivil, NomeConjugue, dNascimentoConjugue, NomeMaeConjugue, ConjugueCPF, cCasamento, nPai, nMae, dNascimento,CodColaborador) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                                $stmt = $conexao->prepare($SQL);
                                $stmt->bindParam(1, $IdCadastro);
                                $stmt->bindParam(2, $IdEndereco);
                                $stmt->bindParam(3, $IdDocumento);
                                $stmt->bindParam(4, $IdContratacao);
                                $stmt->bindParam(5, $IdContato);
                                $stmt->bindParam(6, $Sexo);
                                $stmt->bindParam(7, $Naturalidade);
                                $stmt->bindParam(8, $Cor);
                                $stmt->bindParam(9, $Escolaridade);
                                $stmt->bindParam(10, $eCivl);
                                $stmt->bindParam(11, $nConjugue);
                                $stmt->bindParam(12, $dNascimentoConjugue);
                                $stmt->bindParam(13, $mConjugue);
                                $stmt->bindParam(14, $CPFConjugue);
                                $stmt->bindParam(15, $cCasamento);
                                $stmt->bindParam(16, $nPai);
                                $stmt->bindParam(17, $nMae);
                                $stmt->bindParam(18, $_POST['dNascimento']);
                                $stmt->bindParam(19, $_POST['CodColaborador']);
                                $Colaborador = $stmt->execute();
                            endif;
                            if($Colaborador):
                                $IdColaborador = $conexao->lastInsertId();
                                $Historico = utf8_encode("Admissão");
                                $sql = "INSERT INTO historico (Colaborador_idColaborador, Historico, Data, Cargo) VALUES (?, ?, ?, ?)";
                                $stmt = $conexao->prepare($sql);
                                $stmt->bindParam(1, $IdColaborador);
                                $stmt->bindParam(2, $Historico);
                                $stmt->bindParam(3, $dAdmissao);
                                $stmt->bindParam(4, $Cargo);
                                $stmt->execute();
                                $Chefia = anti_injection($_POST['chefia']);
                                $sql = "INSERT INTO chefia (Colaborador_idColaborador, Usuario_idUsuario) VALUES (?, ?);";
                                $stmt = $conexao->prepare($sql);
                                $stmt->bindParam(1, $IdColaborador);
                                $stmt->bindParam(2, $Chefia);
                                $stmt->execute();
                                if($_POST['dNome1'] == ""):
                                    $SAgencia = utf8_encode(anti_injection($_POST['sAgencia']));
                                        $SBanco = utf8_encode(anti_injection($_POST['sBanco']));
                                        $SConta = str_replace($Trocas,"",utf8_encode(anti_injection($_POST['sConta'])));
                                        $STipo = utf8_encode("Conta Salário");
                                        $SQL = "INSERT INTO conta (Colaborador_idColaborador, Agencia, Conta, Banco, Tipo) VALUES (?,?,?,?,?);";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdColaborador);
                                        $stmt->bindParam(2, $SAgencia);
                                        $stmt->bindParam(3, $SConta);
                                        $stmt->bindParam(4, $SBanco);
                                        $stmt->bindParam(5, $STipo);
                                        $ContaS = $stmt->execute();
                                        if($ContaS):
                                            if($_POST['banco'] == null):        
                                                echo "<script>alert('Cadastrado com Sucesso!');window.location.href='".BASE."cadastros/Colaborador.php';</script>";
                                            else:
                                                $Agencia = utf8_encode(anti_injection($_POST['agencia']));
                                                $Banco = utf8_encode(anti_injection($_POST['banco']));
                                                $Conta = str_replace($Trocas,"",utf8_encode(anti_injection($_POST['conta'])));
                                                $Tipo = utf8_encode(anti_injection($_POST['tipo']));
                                                $SQL = "INSERT INTO conta (Colaborador_idColaborador, Agencia, Conta, Banco, Tipo) VALUES (?,?,?,?,?);";
                                                $stmt = $conexao->prepare($SQL);
                                                $stmt->bindParam(1, $IdColaborador);
                                                $stmt->bindParam(2, $Agencia);
                                                $stmt->bindParam(3, $Conta);
                                                $stmt->bindParam(4, $Banco);
                                                $stmt->bindParam(5, $Tipo);
                                                $Conta = $stmt->execute();
                                                if($Conta):
                                                    echo "<script>alert('Cadastrado com  Sucesso!');window.location.href='".BASE."cadastros/Colaborador.php';</script>";
                                                else:
                                                    $SQL = "DELETE FROM conta WHERE Colaborador_idColaborador = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdColaborador);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM dependente WHERE Colaborador_idColaborador = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdColaborador);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM colaborador WHERE idColaborador = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdColaborador);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM contratacao WHERE idContratacao = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdContratacao);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdEndereco);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM documento WHERE idDocumento = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdDocumento);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdCadastro);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM contato WHERE idContato = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdContato);
                                                    $stmt->execute();
                                                    echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                                                endif;
                                            endif;
                                        else:
                                            $SQL = "DELETE FROM dependente WHERE Colaborador_idColaborador = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdColaborador);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM colaborador WHERE idColaborador = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdColaborador);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM contratacao WHERE idContratacao = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdContratacao);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdEndereco);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM documento WHERE idDocumento = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdDocumento);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdCadastro);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM contato WHERE idContato = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdContato);
                                            $stmt->execute();
                                            echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                                        endif;
                                else:
                                    $SQL = "INSERT INTO dependente (Colaborador_idColaborador, dNome, dNascimento, Registro, Livro, Folha, DNV, dCPF, nMae, Parentesco) VALUES (?,?,?,?,?,?,?,?,?,?);";
                                    $stmt = $conexao->prepare($SQL);
                                    $Itens = 0;
                                    while($x < $cont):
                                        $dNome = utf8_encode(anti_injection($_POST['dNome'.$c[$x]]));
                                        $dFilho = utf8_encode(anti_injection($_POST['dFilho'.$c[$x]]));
                                        $Registro = utf8_encode(anti_injection($_POST['fRegistro'.$c[$x]]));
                                        $fLivro = utf8_encode(anti_injection($_POST['fLivro'.$c[$x]]));
                                        $fFolha = utf8_encode(anti_injection($_POST['fFolha'.$c[$x]]));
                                        $fDNV = utf8_encode(anti_injection($_POST['dnv'.$c[$x]]));
                                        $fMae = utf8_encode(anti_injection($_POST['fMae'.$c[$x]]));
                                        $Parentesco = utf8_encode(anti_injection($_POST['Parentesco'.$c[$x]]));
                                        if($_POST['dCpf'.$c[$x]] == ""):
                                            $fCPF = 0;
                                        else:
                                            $fCPF = str_replace($Trocas,"",$_POST['dCpf'.$c[$x]]);
                                        endif;
                                        $stmt->bindParam(1,$IdColaborador);
                                        $stmt->bindParam(2, $dNome);
                                        $stmt->bindParam(3, $dFilho);
                                        $stmt->bindParam(4, $Registro);
                                        $stmt->bindParam(5, $fLivro);
                                        $stmt->bindParam(6, $fFolha);
                                        $stmt->bindParam(7, $fDNV);
                                        $stmt->bindParam(8, $fCPF);
                                        $stmt->bindParam(9, $fMae);
                                        $stmt->bindParam(10, $Parentesco);
                                        $ItemServ = $stmt->execute();
                                        if($ItemServ):
                                            $Itens +=1;
                                        endif;
                                        $x+=1;
                                    endwhile;
                                    if($Itens == $cont):
                                        $SAgencia = utf8_encode(anti_injection($_POST['sAgencia']));
                                        $SBanco = utf8_encode(anti_injection($_POST['sBanco']));
                                        $SConta = utf8_encode(anti_injection($_POST['sConta']));
                                        $STipo = utf8_encode("Conta Salário");
                                        $SQL = "INSERT INTO conta (Colaborador_idColaborador, Agencia, Conta, Banco, Tipo) VALUES (?,?,?,?,?);";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdColaborador);
                                        $stmt->bindParam(2, $SAgencia);
                                        $stmt->bindParam(3, $SConta);
                                        $stmt->bindParam(4, $SBanco);
                                        $stmt->bindParam(5, $STipo);
                                        $ContaS = $stmt->execute();
                                        if($ContaS):
                                            if($_POST['banco'] == null):        
                                                echo "<script>alert('Cadastrado com Sucesso!');window.location.href='".BASE."cadastros/Colaborador.php';</script>";
                                            else:
                                                $Agencia = utf8_encode(anti_injection($_POST['Agencia']));
                                                $Banco = utf8_encode(anti_injection($_POST['Banco']));
                                                $Conta = utf8_encode(anti_injection($_POST['Conta']));
                                                $Tipo = utf8_encode(anti_injection($_POST['tipo']));
                                                $SQL = "INSERT INTO conta (Colaborador_idColaborador, Agencia, Conta, Banco, Tipo) VALUES (?,?,?,?,?);";
                                                $stmt = $conexao->prepare($SQL);
                                                $stmt->bindParam(1, $IdColaborador);
                                                $stmt->bindParam(2, $Agencia);
                                                $stmt->bindParam(3, $Conta);
                                                $stmt->bindParam(4, $Banco);
                                                $stmt->bindParam(5, $Tipo);
                                                $Conta = $stmt->execute();
                                                if($Conta):
                                                    echo "<script>alert('Cadastrado com  Sucesso!');window.location.href='".BASE."cadastros/Colaborador.php';</script>";
                                                else:
                                                    $SQL = "DELETE FROM conta WHERE Colaborador_idColaborador = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdColaborador);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM depedente WHERE Colaborador_idColaborador = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdColaborador);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM colaborador WHERE idColaborador = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdColaborador);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM contratacao WHERE idContratacao = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdContratacao);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdEndereco);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM documento WHERE idDocumento = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdDocumento);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdCadastro);
                                                    $stmt->execute();
                                                    $SQL = "DELETE FROM contato WHERE idContato = ?;";
                                                    $stmt = $conexao->prepare($SQL);
                                                    $stmt->bindParam(1, $IdContato);
                                                    $stmt->execute();
                                                    echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                                                endif;
                                            endif;
                                        else:
                                            $SQL = "DELETE FROM depedente WHERE Colaborador_idColaborador = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdColaborador);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM colaborador WHERE idColaborador = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdColaborador);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM contratacao WHERE idContratacao = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdContratacao);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdEndereco);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM documento WHERE idDocumento = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdDocumento);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdCadastro);
                                            $stmt->execute();
                                            $SQL = "DELETE FROM contato WHERE idContato = ?;";
                                            $stmt = $conexao->prepare($SQL);
                                            $stmt->bindParam(1, $IdContato);
                                            $stmt->execute();
                                            echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                                        endif;
                                    else:
                                        $SQL = "DELETE FROM colaborador WHERE idColaborador = ?;";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdColaborador);
                                        $stmt->execute();
                                        $SQL = "DELETE FROM depedente WHERE Colaborador_idColaborador = ?;";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdColaborador);
                                        $stmt->execute();
                                        $SQL = "DELETE FROM contratacao WHERE idContratacao = ?;";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdContratacao);
                                        $stmt->execute();
                                        $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdEndereco);
                                        $stmt->execute();
                                        $SQL = "DELETE FROM documento WHERE idDocumento = ?;";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdDocumento);
                                        $stmt->execute();
                                        $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdCadastro);
                                        $stmt->execute();
                                        $SQL = "DELETE FROM contato WHERE idContato = ?;";
                                        $stmt = $conexao->prepare($SQL);
                                        $stmt->bindParam(1, $IdContato);
                                        $stmt->execute();
                                        echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                                    endif;
                                endif;
                            else:
                                $SQL = "DELETE FROM contratacao WHERE idContratacao = ?;";
                                $stmt = $conexao->prepare($SQL);
                                $stmt->bindParam(1, $IdContratacao);
                                $stmt->execute();
                                $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                                $stmt = $conexao->prepare($SQL);
                                $stmt->bindParam(1, $IdEndereco);
                                $stmt->execute();
                                $SQL = "DELETE FROM documento WHERE idDocumento = ?;";
                                $stmt = $conexao->prepare($SQL);
                                $stmt->bindParam(1, $IdDocumento);
                                $stmt->execute();
                                $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                                $stmt = $conexao->prepare($SQL);
                                $stmt->bindParam(1, $IdCadastro);
                                $stmt->execute();
                                $SQL = "DELETE FROM contato WHERE idContato = ?;";
                                $stmt = $conexao->prepare($SQL);
                                $stmt->bindParam(1, $IdContato);
                                $stmt->execute();
                                echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                            endif;
                        else:
                            $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $IdEndereco);
                            $stmt->execute();
                            $SQL = "DELETE FROM documento WHERE idDocumento = ?;";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $IdDocumento);
                            $stmt->execute();
                            $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $IdCadastro);
                            $stmt->execute();
                            $SQL = "DELETE FROM contato WHERE idContato = ?;";
                            $stmt = $conexao->prepare($SQL);
                            $stmt->bindParam(1, $IdContato);
                            $stmt->execute();
                            echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                        endif;
                    else:
                        $SQL = "DELETE FROM endereco WHERE idEndereco = ?;";
                        $stmt = $conexao->prepare($SQL);
                        $stmt->bindParam(1, $IdEndereco);
                        $stmt->execute();
                        $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                        $stmt = $conexao->prepare($SQL);
                        $stmt->bindParam(1, $IdCadastro);
                        $stmt->execute();
                        $SQL = "DELETE FROM contato WHERE idContato = ?;";
                        $stmt = $conexao->prepare($SQL);
                        $stmt->bindParam(1, $IdContato);
                        $stmt->execute();
                        echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                    endif;
                else:
                    $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                    $stmt = $conexao->prepare($SQL);
                    $stmt->bindParam(1, $IdCadastro);
                    $stmt->execute();
                    $SQL = "DELETE FROM contato WHERE idContato = ?;";
                    $stmt = $conexao->prepare($SQL);
                    $stmt->bindParam(1, $IdContato);
                    $stmt->execute();
                    echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                endif;
            else:
                $SQL = "DELETE FROM cadastro WHERE idCadastro = ?;";
                $stmt = $conexao->prepare($SQL);
                $stmt->bindParam(1, $IdCadastro);
                $Remove = $stmt->execute();
                if($Remove):
                    echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
                endif;
            endif;
        else:
             echo "<script>alert('Falha ao cadastrar!');window.setTimeout('history.go(-1)', 0);</script>";
        endif;
    endif;
?>